# Generated by Django 4.2.30 on 2026-07-24 12:12

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('file_type', models.CharField(default='txt', max_length=20)),
                ('domain_type', models.CharField(choices=[('educational', 'Educational'), ('programming', 'Programming'), ('auto_detect', 'Auto Detect')], default='auto_detect', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('code_mode', models.CharField(choices=[('skip', 'Skip Code'), ('summarize', 'Summarize Code'), ('read_clean', 'Read Signature & Clean')], default='summarize', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('optimized_speech_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('optimized_text', models.TextField(blank=True)),
                ('estimated_duration_seconds', models.PositiveIntegerField(default=0)),
                ('document', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
