# Generated by Django 6.0.7 on 2026-07-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='additional_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of selected OptimizationPreference values.'),
        ),
    ]
