# Generated by Django 6.0.7 on 2026-08-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='optimization_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=20),
        ),
    ]
