# Generated by Django 6.0.7 on 2026-08-14 23:19

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_optimization_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkAudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(upload_to='audio_chunks/')),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_recording', to='documents.documentchunk')),
            ],
            options={
                'verbose_name': 'Chunk Audio Recording',
                'verbose_name_plural': 'Chunk Audio Recordings',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
