# Generated by Django 6.0.7 on 2026-08-21 06:08

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_chunkaudiorecording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRegexRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_type', models.CharField(choices=[('educational', 'Educational'), ('programming', 'Programming'), ('auto_detect', 'Auto Detect')], max_length=30)),
                ('pattern', models.TextField()),
                ('replacement', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regex_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Optimization Regex Rule',
                'verbose_name_plural': 'Optimization Regex Rules',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserOptimizationExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_type', models.CharField(choices=[('educational', 'Educational'), ('programming', 'Programming'), ('auto_detect', 'Auto Detect')], max_length=30)),
                ('raw_text', models.TextField()),
                ('edited_text', models.TextField()),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_examples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Optimization Example',
                'verbose_name_plural': 'User Optimization Examples',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
