# Generated by Django 6.0.7 on 2026-09-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_optimizationregexrule_useroptimizationexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='is_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
