# Generated by Django 6.0.7 on 2026-09-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentchunk_is_recording_alter_documentchunk_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='is_user_created',
            field=models.BooleanField(default=False),
        ),
    ]
