# Generated by Django 6.0.7 on 2026-09-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The original price of the new plan', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prorated_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied from unused previous plan time', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('initial', 'Initial'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], default='initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The final amount charged (base_amount - prorated_discount)', max_digits=10),
        ),
    ]
