# Generated by Django 6.0.7 on 2026-08-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_plan_pricing_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
