# Generated by Django 6.0.7 on 2026-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_pricing_plan_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audio_speed',
            field=models.DecimalField(choices=[(0.5, '0.5x - Very Slow'), (0.75, '0.75x - Slow'), (1.0, '1.0x - Normal'), (1.25, '1.25x - Fast'), (1.5, '1.5x - Very Fast'), (2.0, '2.0x - Extremely Fast')], decimal_places=2, default=1.0, max_digits=3, verbose_name='Audio Playback Speed'),
        ),
    ]
