# Generated by Django 6.0.7 on 2026-08-18 12:28

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_audio_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='audio_speed',
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_speed', models.DecimalField(choices=[(0.5, '0.5x - Very Slow'), (0.75, '0.75x - Slow'), (1.0, '1.0x - Normal'), (1.25, '1.25x - Fast'), (1.5, '1.5x - Very Fast'), (2.0, '2.0x - Extremely Fast')], decimal_places=2, default=1.0, max_digits=3, verbose_name='Audio Playback Speed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
