# Generated by Django 6.0.7 on 2026-08-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_audio_speed_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='auto_play',
            field=models.BooleanField(default=False, verbose_name='Auto-Play Audio'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_voice',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Default TTS Voice'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_family',
            field=models.CharField(choices=[('font-sans', 'Sans-Serif (Default)'), ('font-serif', 'Serif'), ('font-mono', 'Monospace (Dyslexia Friendly)')], default='sans', max_length=50, verbose_name='Reading Font Family'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('text-sm', 'Small'), ('text-base', 'Medium'), ('text-lg', 'Large'), ('text-xl', 'Extra Large')], default='medium', max_length=20, verbose_name='Reading Font Size'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='layout_density',
            field=models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', max_length=20, verbose_name='Layout Density'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reduce_motion',
            field=models.BooleanField(default=False, verbose_name='Reduce Motion'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('system', 'System Default')], default='system', max_length=20, verbose_name='App Theme'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='visual_highlight_style',
            field=models.CharField(choices=[('bg-yellow-200', 'Yellow Background'), ('bg-brand/20', 'Red Background'), ('underline', 'Underline'), ('text-brand font-bold', 'Bold Text')], default='bg-yellow-200', max_length=20, verbose_name='Highlight Style'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='voice_pitch',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Voice Pitch'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='voice_volume',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Voice Volume'),
        ),
    ]
