# Generated by Django 6.0.7 on 2026-08-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersettings_auto_play_usersettings_default_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='chunk_size',
            field=models.CharField(choices=[('100', 'Small (~100 words)'), ('250', 'Medium (~250 words)'), ('500', 'Large (~500 words)')], default='250', max_length=10, verbose_name='Document Chunk Size'),
        ),
    ]
