# Generated by Django 6.0.7 on 2026-08-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usersettings_chunk_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_voice',
            field=models.CharField(choices=[('alloy', 'Alloy (Neutral)'), ('echo', 'Echo (Male)'), ('fable', 'Fable (Male, British)'), ('onyx', 'Onyx (Male, Deep)'), ('nova', 'Nova (Female)'), ('shimmer', 'Shimmer (Female)')], default='alloy', max_length=50, verbose_name='Default TTS Voice'),
        ),
    ]
