# Generated by Django 6.0.7 on 2026-09-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usersettings_default_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_tries_used',
            field=models.IntegerField(default=0),
        ),
    ]
