#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --noinput
python manage.py migrate --noinput

exec gunicorn config.wsgi --bind 0.0.0.0:${PORT:-5000} --chdir=/app --workers 4 --threads 4
